[package]
name = "chickenz-host"
version = "0.1.0"
edition = "2021"

[dependencies]
chickenz-core = { path = "../core" }
chickenz-methods = { path = "../methods" }
risc0-zkvm = { version = "3.0", features = ["prove", "metal"] }
serde = { workspace = true }
serde_json = "1"
hex = "0.4"
